models/article.py
from . import Model
import time
from utils import local_time


class Article(Model):
    def __init__(self, form):
        self.id = None
        self.content = form.get('content', '')
        self.title = form.get('title', '')
        self.creat_time = int(time.time())
        self.upgrade_time = self.creat_time
        self.categorie = form.get('categorie', '')
        self.tags = form.get('tags', '').split(' ')

    def local_time(self):
        format = '%Y-%m-%d'
        value = time.localtime(self.upgrade_time)
        dt = time.strftime(format, value)
        return dt

    def time_y_m_d(self):
        return self.local_time().split('-')

    @classmethod
    def years_mouths_dates_find_all(cls, **kwargs):
        arts = cls.find_all(**kwargs)
        ys = set()
        ms = set()
        ds = set()
        for art in arts:
            y_m_d = art.time_y_m_d()
            ys.add(y_m_d[0])
            ms.add(y_m_d[1])
            ds.add(y_m_d[2])
        return ys, ms, ds

    @classmethod
    def years_mouths_dates(cls, arts):
        ys = set()
        ms = set()
        ds = set()
        for art in arts:
            y_m_d = art.time_y_m_d()
            ys.add(y_m_d[0])
            ms.add(y_m_d[1])
            ds.add(y_m_d[2])
        return ys, ms, ds

    @classmethod
    def years_mouths_dates_all(cls):
        arts = cls.all()
        ys = set()
        ms = set()
        ds = set()
        for art in arts:
            y_m_d = art.time_y_m_d()
            ys.add(y_m_d[0])
            ms.add(y_m_d[1])
            ds.add(y_m_d[2])
        return ys, ms, ds

    def get_comments(self):
        from .comment import Comment
        comments = Comment.find_all(article_id=self.id)
        return comments

routes/article.py
from flask import Blueprint, request, render_template, url_for, redirect, abort

from models.article import Article
from models.comment import Comment
main = Blueprint('article', __name__)


@main.route('/<int:id>')
def article_detail(id):
    a = Article.find(id)
    if a is None:
        abort(404)
    return render_template('article.html', article=a)


@main.route('/add-comment', methods=['POST'])
def add_comment():
    form = request.form
    c = Comment(form)
    article_id = request.args.get('id')
    c.article_id = int(article_id)
    c.save()
    return redirect(url_for('article.article_detail', id=article_id))

templates/_aside.html
<aside id="sidebar">
    <div class="widget-wrap">
        <h3 class="widget-title">分类</h3>
        <div class="widget">
            <ul class="category-list">
       
                <li class="category-list-item"><a class="category-list-link" href="/categories/技术/">技术</a><span
                        class="category-list-count">3</span></li>
            </ul>
        </div>
    </div>


    <div class="widget-wrap">
        <h3 class="widget-title">标签</h3>
        <div class="widget">
            <ul class="tag-list">
                <li class="tag-list-item"><a class="tag-list-link" href="/tags/Hexo/">Hexo</a><span
                        class="tag-list-count">1</span></li>
                <li class="tag-list-item"><a class="tag-list-link" href="/tags/IOS/">IOS</a><span
                        class="tag-list-count">2</span></li>
                <li class="tag-list-item"><a class="tag-list-link" href="/tags/Octopress/">Octopress</a><span
                        class="tag-list-count">1</span></li>
            </ul>
        </div>
    </div>


    <div class="widget-wrap">
        <h3 class="widget-title">标签云</h3>
        <div class="widget tagcloud">
            <a href="/tags/Hexo/" style="font-size: 10px;">Hexo</a> <a href="/tags/IOS/"
                                                                       style="font-size: 20px;">IOS</a> <a
                href="/tags/Octopress/" style="font-size: 10px;">Octopress</a>
        </div>
    </div>


    <div class="widget-wrap">
        <h3 class="widget-title">归档</h3>
        <div class="widget">
            <ul class="archive-list">
                <li class="archive-list-item"><a class="archive-list-link" href="/archives/2017/03/">三月 2017</a><span
                        class="archive-list-count">2</span></li>
                <li class="archive-list-item"><a class="archive-list-link" href="/archives/2017/01/">一月 2017</a><span
                        class="archive-list-count">1</span></li>
            </ul>
        </div>
    </div>


    <div class="widget-wrap">
        <h3 class="widget-title">近期文章</h3>
        <div class="widget">
            <ul>

                <li>
                    <a href="/2017/03/02/udacity课程ios开发实践项目2 - 机器人迷宫2/">Udacity课程ios开发实践项目2 - 机器人迷宫2</a>
                </li>

                <li>
                    <a href="/2017/03/02/udacity课程ios开发实践项目1-海盗舰队1/">Udacity课程ios开发实践项目1-海盗舰队1</a>
                </li>

                <li>
                    <a href="/2017/01/15/Hexo与Octopress搭建博客的比较/">Hexo与Octopress搭建博客的比较</a>
                </li>

            </ul>
        </div>
    </div>
</aside>

templates/_comment_add.html
    <div>
        <h1 class="widget-title" style="font-size: medium">添加评论</h1>
        <form class="widget" method="post" action="{{ url_for('article.add_comment', id=1) }}">
            <div>
                <input class="input-xlarge" type="text" name="nickname" placeholder="昵称">
                <input class="input-xlarge" type="text" name="email" placeholder="邮箱">
            </div>
            <div>
                <textarea rows="8" name="content" placeholder="添加评论" style="width:;width: -webkit-fill-available;"></textarea>
            </div>
            <button class="btn btn-primary" type="submit">提交</button>
        </form>
    </div>

templates/about.html
{% extends "base.html" %}
{% block div %}
<section id="main">
    <article id="page-undefined" class="article article-type-page" itemscope="" itemprop="blogPost">
        <div class="article-meta">
            <a href="/About/index.html" class="article-date">
                <time datetime="2017-01-15T06:22:38.000Z" itemprop="datePublished">2017-01-15</time>
            </a>
        </div>
        <div class="article-inner">
            <header class="article-header">
                <h1 class="article-title" itemprop="name">
                    About
                </h1>
            </header>
            <div class="article-entry" itemprop="articleBody">
                <blockquote>
                    <p>石孟，现处成都</p>
                    <p>哈哈哈</p>
                </blockquote>
                <hr>
                <p>哈哈哈</p>
                <p>哈哈哈</p>
            </div>

        </div>
    </article>
    {% include "_comment_add.html" %}
</section>
{% include '_aside.html' %}
{% endblock %}

templates/archives.html
{% extends "base.html" %}
{% block div %}
    <section id="main">
        <section class="archives-wrap">
            {% for y in ys %}
                <div class="archive-year-wrap">
                    <a href="/archives/2017" class="archive-year">{{ y }}</a>
                </div>

                <div class="archives">
                   {% for a in articles if a.time_y_m_d()[0] == y %}
                    <article class="archive-article archive-type-post">
                        <div class="archive-article-inner">
                            <header class="archive-article-header">
                                <a href="/2017/03/02/udacity课程ios开发实践项目2 - 机器人迷宫2/" class="archive-article-date">
                                    <time datetime="2017-03-02T08:39:00.000Z" itemprop="datePublished">{{ a.time_y_m_d()[1] }}月{{ a.time_y_m_d()[2] }}日</time>
                                </a>
                                <h1 itemprop="name">
                                    <a class="archive-article-title" href="/2017/03/02/udacity课程ios开发实践项目2 - 机器人迷宫2/">{{ a.title }}</a>
                                </h1>
                            </header>
                        </div>
                    </article>
                    {% endfor %}
                </div>
            {% endfor %}
        </section>
    </section>
    {% include "_aside.html" %}
{% endblock %}

templates/article.html
{% extends "base.html" %}
{% block div %}
<section id="main">
    <article id="page-undefined" class="article article-type-page" itemscope="" itemprop="blogPost">
        <div class="article-meta">
            <a href="/About/index.html" class="article-date">
                <time>{{ article.local_time() }}</time>
            </a>
        </div>
        <div class="article-inner">
            <header class="article-header">
                <h1 class="article-title" itemprop="name">
                    {{ article.title }}
                </h1>
            </header>
            <div class="article-entry" itemprop="articleBody">
                {{ article.content }}
            </div>

        </div>
    </article>
    <nav id="article-nav">

        <a href="/2017/03/02/udacity课程ios开发实践项目2 - 机器人迷宫2/" id="article-nav-newer" class="article-nav-link-wrap">
            <strong class="article-nav-caption">下一篇</strong>
            <div class="article-nav-title">

                Udacity课程ios开发实践项目2 - 机器人迷宫2

            </div>
        </a>


        <a href="/2017/01/15/Hexo与Octopress搭建博客的比较/" id="article-nav-older" class="article-nav-link-wrap">
            <strong class="article-nav-caption">上一篇</strong>
            <div class="article-nav-title">Hexo与Octopress搭建博客的比较</div>
        </a>

    </nav>

     <div style="margin-bottom: 10px;" >
        <h1 class="widget-title" style="font-size: medium">评论列表</h1>
        <ul class="widget">
            {% if article.get_comments() %}
            {% for c in article.get_comments() %}
            <li >
                <div>
                    <a href="/user/%E7%9F%B3%E5%AD%9F">
                        <img class="img-rounded profile-thumbnail" src="http://www.gravatar.com/avatar/2436aa672443983b81526ae5391c3ece?s=40&amp;d=identicon&amp;r=g">
                    </a>
                </div>
                <div class>
                <div><span class="" data-timestamp="2018-11-20T07:47:10Z" data-format="fromNow(0)" data-refresh="0" style="">2 months ago</span></div>
                <div><a href="/user/%E7%9F%B3%E5%AD%9F">{{ c.nickname }}</a></div>
                <div>
                    {{ c.content }}
                </div>
                </div>
             </li>
            {% endfor %}
            {% else %}
            暂时还没有评论
            {% endif %}
        </ul>
    </div>


    {% include "_comment_add.html"%}
</section>
{% include "_aside.html" %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">

    <title>Shimeng's Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta name="description" content="石孟 的个人博客">
    <meta property="og:type" content="website">
    <meta property="og:title" content="Shi Meng's Blog">
    <meta property="og:url" content="http://weicfd.github.io/index.html">
    <meta property="og:site_name" content="Shi Meng's Blog">
    <meta property="og:description" content="石孟 的个人博客">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="Shi Meng's Blog">
    <meta name="twitter:description" content="石孟 的个人博客">

    <link rel="alternative" href="/atom.xml" title="Shi meng's Blog" type="application/atom+xml">


    <link rel="icon" href="/favicon.png">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.min.js"></script><![endif]-->

    <!-- 加载gitment的css和js文件 -->
    <script src="/static/js/gitment.js"></script>
    <script src="//bdimg.share.baidu.com/static/api/js/share.js?cdnversion=429415"></script>
</head>
<body>
<div id="container">
    <div id="wrap">
        <header id="header">
            <div id="banner"></div>
            <div id="header-outer" class="outer">
                <div id="header-title" class="inner">
                    <h1 id="logo-wrap">
                        <a href="/" id="logo">Shi Meng's Blog</a>
                    </h1>

                    <h2 id="subtitle-wrap">
                        <a href="/" id="subtitle">我ら思う、故に我ら在り</a>
                    </h2>

                </div>
                <div id="header-inner" class="inner">
                    <nav id="main-nav">
                        <a id="main-nav-toggle" class="nav-icon"></a>

                        <a class="main-nav-link" href="/">Home</a>

                        <a class="main-nav-link" href="/archives">Archives</a>

                        <a class="main-nav-link" href="/about">About</a>

                    </nav>
                    <nav id="sub-nav">

                        <a id="nav-rss-link" class="nav-icon" href="/atom.xml" title="RSS Feed"></a>

                        <a id="nav-search-btn" class="nav-icon" title="Search"></a>
                    </nav>
                    <div id="search-form-wrap">
                        <form action="//www.baidu.com/baidu" method="get" accept-charset="utf-8" class="search-form">
                            <input type="search" name="word" maxlength="20" class="search-form-input"
                                   placeholder="Search">
                            <input type="submit" value="" class="search-form-submit">
                            <input name="tn" type="hidden" value="bds">
                            <input name="cl" type="hidden" value="3">
                            <input name="ct" type="hidden" value="2097152">
                            <input type="hidden" name="si" value="weicfd.github.io">
                        </form>
                    </div>
                </div>
            </div>
        </header>
        <div class="outer">
            {% block div %}
            {% endblock %}
        </div>
        <footer id="footer">

            <div class="outer">
                <div id="footer-info" class="inner">
                    ©2018 Shi Meng<br>
                    Powered by <a href="//hexo.io/" target="_blank">Hexo</a>
                    .
                    Theme by <a href="https://github.com/xiangming/landscape-plus" target="_blank">Landscape-plus</a>
                </div>
            </div>
        </footer>
    </div>
    <nav id="mobile-nav">

        <a href="/" class="mobile-nav-link">Home</a>

        <a href="/archives" class="mobile-nav-link">Archives</a>

        <a href="/About" class="mobile-nav-link">About</a>

    </nav>
    <!-- totop start -->
    <div id="totop">
        <a title="返回顶部"><img src="/img/scrollup.png"></a>
    </div>

    <!-- totop end -->


    <!-- 百度分享 start -->

    <div id="article-share-box" class="article-share-box">
        <div id="bdshare" class="bdsharebuttonbox article-share-links">
            <a class="article-share-weibo" data-cmd="tsina" title="分享到新浪微博"></a>
            <a class="article-share-weixin" data-cmd="weixin" title="分享到微信"></a>
            <a class="article-share-qq" data-cmd="sqq" title="分享到QQ"></a>
            <a class="article-share-renren" data-cmd="renren" title="分享到人人网"></a>
            <a class="article-share-more" data-cmd="more" title="更多"></a>
        </div>
    </div>
    <script>
  function SetShareData(cmd, config) {
    if (shareDataTitle && shareDataUrl) {
      config.bdText = shareDataTitle;
      config.bdUrl = shareDataUrl;
    }
    return config;
  }
  window._bd_share_config={
    "common":{onBeforeClick: SetShareData},
    "share":{"bdCustomStyle":"/css/bdshare.css"}
  };
  with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='//bdimg.share.baidu.com/static/api/js/share.js?cdnversion='+~(-new Date()/36e5)];

    </script>

    <!-- 百度分享 end -->

    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>


    <script src="/js/script.js"></script>

</div>


</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block div%}
    <section id="main">
        {% for a in articles %}
        <article id="post-udacity" class="article article-type-post" itemscope="" itemprop="blogPost">
            <div class="article-meta">
                <a href="{{ url_for('article.article_detail', id=a.id) }}" class="article-date">
                    <time datetime="2017-03-02T08:39:00.000Z" itemprop="datePublished">{{ a.local_time() }}</time>
                </a>
                <div class="article-category">
                    <a class="article-category-link" href="/categories/技术/">{{ a.categorie }}</a>
                </div>
            </div>
            <div class="article-inner">
                <header class="article-header">
                    <h1 itemprop="name">
                        <a class="article-title" href="{{ url_for('article.article_detail', id=a.id) }}">{{ a.title }}</a>
                    </h1>
                </header>
                <div class="article-entry" itemprop="articleBody">
                    {{ a.content }}
                    <p class="article-more-link">
                        <a href="{{ url_for('article.article_detail', id=a.id) }}">Read More</a>
                    </p>
                </div>
                <footer class="article-footer">
                    {% if a.tags %}
                    <ul class="article-tag-list">

                        {% for tag in a.tags %}
                        <li class="article-tag-list-item"><a class="article-tag-list-link" href="/tags/IOS/">{{ tag }}</a></li>
                        {% endfor %}

                    </ul>
                    {% endif %}
                </footer>
            </div>
            <div id="gitment"></div>
            <!-- 主页不要加载gitment -->
        </article>
        {% endfor %}
    </section>
    {% include '_aside.html' %}
{% endblock %}